### ISSUE TITLE
CryOre not generating during overlapping rockfall in exposed cavern

### ISSUE THREAD

**Issue by trigger-segfault** [trigger-segfault/OpenLRR#54]
**Describe the issue**
The exact cause of this bug isn't entirely understood, so the *rockfall* title is partially an assumption. When digging walls in *Driller Night!* using debug keys, it's possible to dig walls in a way that CryOre for destroyed adjacent blocks won't spawn. This only happens when digging in fast succession right after discovering the ToolStore hidden cavern.

**Expected behaviour**
CryOre should normally spawn from dug blocks, but something is stoppinp/overwriting it from happening.

**Steps to reproduce**
1. Start up *Driller Night!* with AllowDebugKeys enabled.
2. Using the DestroyWall debug key, destroy walls up and then immediately left.
3. Destroy the final left wall to uncover the cavern.
4. Then quickly destroy the inner-right side of the remaining 2x2 wall section while the cavern discovery/rockfall is still happening.
5. After the dust has settled, crystals should not spawn, (as long as the wall you destroyed was the one shown over the cursor in the Figure B screenshot).

**Additional information**
* **Time played this session:** 1 minute.
* **Level:** Driller Night!
* **Game speed:** 100%
* **Graphics fix:** dgVoodoo 2.55.4
* **Using mods:** None

***

**Screenshots**
*Figure A (left): The mouse is over the wall that was destroyed to uncover the hidden cavern.*
*Figure B (right): The mouse is over the wall destroyed to tear down the 2x2 section while preventing crystals from spawning.*
![OpenLRR_CryOreMissingRockFallOverlap](https://user-images.githubusercontent.com/9752430/188207714-af606512-8881-4c74-adb4-710c9389df04.png)

**Comment by RingtailRaider** [comment]
This bug seems to happen if more than four walls collapse at once. If a large area of rock is collapsed within the span of a couple of seconds, only the first four that fell, or the four closes to the wall drilled that caused the rest to collapse, will spawn from their CryOre map, while the rest won't. Once the rockfall animations have completed and the CryOre generation has happened, it resets.

From what I've seen, landslides _do_ count towards this if they happen right before some walls are drilled, despite them not generating from either the CryOre map or PTL script. I don't know if those super landslides that generate a 2x3 rubble area (are those cave-ins?) count as 4+ collapses.

While I hadn't ever noticed it in the original game, there are a number of custom maps where I've encountered this to an extreme extent (one in particular where the entire outline of a cave collapsed and generated almost none of the crystals it was supposed to have), which is what made me aware of it.

**Comment by trigger-segfault** [comment]
So this is an issue with the Effects module.

All levels define `GenerateFromCryore` as the action produced by `RockFallComplete` in their PTL. The `RockFallComplete` message is produced by the Effects module telling the game how many rockfall effects have finished animating this update. The problem is the Effects module can only store up to 4 of each rockfall effect type, so when 4 effects are already in use, any new `RockFallComplete` messages will slip into the void.

**Functions that need to be implemented:**
* `Effect_Load_RockFallStyle`
* `Effect_Spawn_RockFall`
* `Effect_UpdateAll`
* `Effect_Unk_RockFall_FUN_0040c4e0`
* `Effect_RemoveAll_RockFall`
* `Level_UpdateEffects` (responsible for the `RockFallComplete` message, but doesn't need to be changed)

In order to fix this, either a variable amount of rockfall effects need to be supported, or the Effects module needs timers to track rockfall effects that aren't displayed.
